# Use the official unprivileged NGINX image
FROM nginxinc/nginx-unprivileged:stable-alpine

# Copy your static site content into the NGINX web root
# COPY ./html /usr/share/nginx/html
COPY ./html/index.html /usr/share/nginx/html/index.html
