site_name: My Docs
copyright: Copyright &copy; Oriana Schwickrath 2025
site_url: https://trainings.com
theme:
  name: material
  favicon: assets/images/Kubernetes_logo.png
  font:
    text: Merriweather Sans # Google Font (Schriftart
    code: Red Hat Mono # Google Font (Code Schriftart)
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light green
      accent: teal

nav:
  - "Home": index.md
  - "Basics": kubernetes-basics.md
    - "Docker/ Podman": 
    - "First Hands-On Lab": 
  - "Orchestration":
    - "Minikube":
    - "Second Hands-On Lab":
  - "Enterprise Solutions":
    - "Red Hat OpenShift": 
    - "Third Hands-On Lab": 



