site_name: My Docs
copyright: Copyright &copy; Oriana Schwickrath 2025
site_url: https://trainings.com
theme:
  name: material
  favicon: assets/images/Kubernetes_logo.png
  font:
    text: Merriweather Sans # Google Font (Schriftart
    code: Red Hat Mono # Google Font (Code Schriftart)
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light green
      accent: teal

nav:
  - "Home": index.md
  - "Basics": 
    - kubernetes-basics.md
    - "First Hands-On Lab": kubernetes-core/first-lab.md
  - "Orchestration": 
    - orchestration.md
    - "Second Hands-On Lab": kubernetes-core/second-lab.md
  - "Enterprise Solutions":
    - enterprise-solutions.md
    - "Third Hands-On Lab": kubernetes-core/third-lab.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg




